version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    depends_on:
      - prometheus